name: iSAG
favicon: null
layout_spectrum: 0.47844284283928573
typography_spectrum: 0.6805019394960254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8407509389799088
  lightness: 0.10517914546653628
  saturation: 0.1672406152356416
  rhythmicContrast: 0.9387638070620596
purpose: []
