name: iSAG
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48378
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe4bc'
    - '#140d07'
    - '#866640'
    - '#dda248'
    - '#c03f1f'
  brandStrength: 0.6875
  lightness: 0.3125
  saturation: 0.4375
  rhythmicContrast: 0.9387638070620596
purpose: []
